export const PATHS = {
  login: '/login',
  home: '/',
  register: '/register',
  findPassword: '/find-password',
  accept: '/accept',
  member: '/member',
  myPage: '/mypage',
  dues: '/dues',
  duesSetup: '/dues-setup',
  editDues: '/edit-dues',
  track: '/track',
  role: '/role',
  reservation: '/reservation',
};
